# Generated by Django 4.2.26 on 2025-11-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='user_type',
            field=models.CharField(default='customer', max_length=100),
        ),
    ]
