# Generated by Django 4.2.26 on 2025-11-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='multiVenders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vender_name', models.CharField(max_length=100)),
                ('restaurent_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('restaurent_lic', models.ImageField(blank=True, null=True, upload_to='licience_pics')),
                ('restaurent_img', models.ImageField(blank=True, null=True, upload_to='restaurent_pics')),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
