# Generated by Django 4.2.26 on 2025-11-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venders', '0002_multivenders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='multivenders',
            name='user_type',
            field=models.CharField(default='vender', max_length=100),
        ),
    ]
