# Generated by Django 4.2.26 on 2025-12-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venders', '0004_alter_multivenders_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multivenders',
            name='vender_name',
        ),
        migrations.AlterField(
            model_name='multivenders',
            name='user_type',
            field=models.CharField(default='vender', editable=False, max_length=100),
        ),
    ]
