# Generated by Django 4.2.26 on 2025-12-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venders', '0005_remove_multivenders_vender_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('food_desc', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('food_img', models.ImageField(null=None, unique=None, upload_to='foodimg')),
            ],
        ),
    ]
