# Generated by Django 4.2.26 on 2025-12-02 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venders', '0006_fooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='vender',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='venders.multivenders'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
