# Generated by Django 4.2.26 on 2025-12-03 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venders', '0007_fooditem_vender_alter_fooditem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_img',
            field=models.ImageField(blank=True, null=True, upload_to='foodimg'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='vender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='venders.multivenders'),
        ),
    ]
