# Generated by Django 4.2.26 on 2025-12-05 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venders', '0007_fooditem_vender_alter_fooditem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('food_desc', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('food_img', models.ImageField(blank=True, null=True, upload_to='foodimg')),
                ('vender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='venders.multivenders')),
            ],
        ),
        migrations.DeleteModel(
            name='foodItem',
        ),
    ]
